### DISCUSSION TITLE
Help with Error while dialing: dial unix /run/topolvm/lvmd.sock

### DISCUSSION THREAD

**Discussion by magick93** [topolvm/topolvm#1046] [Q&A] [answered]
Hi

I'm using v15.5.5.

I'm not sure where I'm going wrong. I'm running on microk8s, and used the following `values.yaml` file:

```yaml
node:
  # node.lvmdEmbedded -- Specify whether to embed lvmd in the node container.
  # Should not be used in conjunction with lvmd.managed otherwise lvmd will be started twice.
  lvmdEmbedded: false
  # node.lvmdSocket -- Specify the socket to be used for communication with lvmd.
  lvmdSocket: /run/topolvm/lvmd.sock
  # node.kubeletWorkDirectory -- Specify the work directory of Kubelet on the host.
  # For example, on microk8s it needs to be set to `/var/snap/microk8s/common/var/lib/kubelet`
  kubeletWorkDirectory: /var/snap/microk8s/common/var/lib/kubelet

```

The logs from the deamonset are:

```j
Defaulted container "topolvm-node" out of: topolvm-node, csi-registrar, liveness-probe
{"level":"info","ts":"2025-05-16T05:44:33Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2025-05-16T05:44:33Z","logger":"controller-runtime.metrics","msg":"Starting metrics server"}
{"level":"info","ts":"2025-05-16T05:44:33Z","logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":8080","secure":false}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Starting EventSource","controller":"logicalvolume","controllerGroup":"topolvm.io","controllerKind":"LogicalVolume","source":"kind source: *v1.LogicalVolume"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Starting Controller","controller":"logicalvolume","controllerGroup":"topolvm.io","controllerKind":"LogicalVolume"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Starting workers","controller":"logicalvolume","controllerGroup":"topolvm.io","controllerKind":"LogicalVolume","worker count":1}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Stopping and waiting for non leader election runnables"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Stopping and waiting for leader election runnables"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"logicalvolume","controllerGroup":"topolvm.io","controllerKind":"LogicalVolume"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"All workers finished","controller":"logicalvolume","controllerGroup":"topolvm.io","controllerKind":"LogicalVolume"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Stopping and waiting for caches"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Stopping and waiting for webhooks"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Stopping and waiting for HTTP servers"}
{"level":"info","ts":"2025-05-16T05:44:33Z","logger":"controller-runtime.metrics","msg":"Shutting down metrics server with timeout of 1 minute"}
{"level":"info","ts":"2025-05-16T05:44:33Z","msg":"Wait completed, proceeding to shutdown the manager"}
{"level":"error","ts":"2025-05-16T05:44:33Z","logger":"setup","msg":"problem running manager","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/topolvm/lvmd.sock: connect: no such file or directory\"","stacktrace":"github.com/topolvm/topolvm/cmd/topolvm-node/app.subMain\n\t/workdir/cmd/topolvm-node/app/run.go:159\ngithub.com/topolvm/topolvm/cmd/topolvm-node/app.init.func1\n\t/workdir/cmd/topolvm-node/app/root.go:41\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/topolvm/topolvm/cmd/topolvm-node/app.Execute\n\t/workdir/cmd/topolvm-node/app/root.go:48\nmain.main\n\t/workdir/cmd/hypertopolvm/main.go:42\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/topolvm/lvmd.sock: connect: no such file or directory"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/topolvm/lvmd.sock: connect: no such file or directory"
```

And the other pods logs are:

```
{"level":"info","ts":"2025-05-16T05:47:04Z","msg":"configuration file loaded","device_classes":[{"name":"ssd","volume-group":"myvg1","default":true,"spare-gb":10,"stripe":null,"stripe-size":"","lvcreate-options":null,"type":"","thin-pool":null}],"socket_name":"/run/topolvm/lvmd.sock","file_name":"/etc/topolvm/lvmd.yaml"}
not found
{"level":"error","ts":"2025-05-16T05:47:04Z","msg":"volume group not found","volume_group":"myvg1","error":"not found","stacktrace":"github.com/topolvm/topolvm/cmd/lvmd/app.subMain\n\t/workdir/cmd/lvmd/app/root.go:85\ngithub.com/topolvm/topolvm/cmd/lvmd/app.init.func2\n\t/workdir/cmd/lvmd/app/root.go:58\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/topolvm/topolvm/cmd/lvmd/app.Execute\n\t/workdir/cmd/lvmd/app/root.go:188\nmain.main\n\t/workdir/cmd/hypertopolvm/main.go:38\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
Error: not found
```

Any help is appreciated.
