### DISCUSSION TITLE
No Scheduler and no Storage Capacity Tracking

### DISCUSSION THREAD

**Discussion by dp-42** [topolvm/topolvm#681] [Q&A] [answered]
Hi,

we use TopoLVM for some pretty specific workloads that we "pin" directly on a node anyway - therefore we are wondering if we can disable the scheduling component completely?

I think it would work this way:

```yaml
<snip>
controller:
  storageCapacityTracking:
    enabled: false
<snip>
scheduler:
  enabled: false
<snip>
webhook:
  podMutatingWebhook:
    enabled: false
  pvcMutatingWebhook:
    enabled: false
<snip>
```

Is this a "supported" way of have TopoLVM running?

I am a bit unsure regarding the `pvcMutatingWebhook` - as in the [docs](https://github.com/topolvm/topolvm/tree/main/deploy#use-storage-capacity-tracking) this is never disabled and seem to be required in both "scheduling modes"? What does it actually do? 

Many thanks!
