### DISCUSSION TITLE
can't deploy pod with pvc

### DISCUSSION THREAD

**Discussion by simonebenati** [topolvm/topolvm#732] [Q&A] [answered]
Hello,

I have deployed correctly every topolvm component. Everything is up and running but when I try to deploy a pod with a pv.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: topolvm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: ubuntu:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-volume
              mountPath: /data
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc
      tolerations:
      - key: "database"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
```
The cluster is not able to provision a pod because:

`default-scheduler  0/7 nodes are available: 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 4 Insufficient topolvm.io/capacity. preemption: 0/7 nodes are available: 3 Preemption is not helpful for scheduling, 4 No preemption victims found for incoming pod.`

Is anyone able to provide help on this matter? I don't understand what Insufficient topolvm.io/capacity is.. I checked all the documentation but couldn't find much on it
