### DISCUSSION TITLE
lvmd does not recognize volume group

### DISCUSSION THREAD

**Discussion by ryanfaircloth** [topolvm/topolvm#815] [Q&A] [answered]
Output from pvdisplay
```
debug-pv-pod:/# pvdisplay 
  --- Physical volume ---
  PV Name               /dev/nvme1n1
  VG Name               instancestore
  PV Size               <872.65 GiB / not usable 4.83 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              223397
  Free PE               223397
  Allocated PE          0
  PV UUID               M6L8Ul-AYKH-5BV1-vGzH-fKgz-DtoV-Ip0Aph
```

output from lvmd
```
{"level":"info","ts":"2024-01-14T12:52:45Z","msg":"configuration file loaded","device_classes":[{"name":"default","volume-group":"instancestore","default":true,"spare-gb":10,"stripe":null,"stripe-size":"","lvcreate-options":null,"type":"","thin-pool":null}],"socket_name":"/run/topolvm/lvmd.sock","file_name":"/etc/topolvm/lvmd.yaml"}
{"level":"info","ts":"2024-01-14T12:52:45Z","msg":"invoking LVM command","args":["fullreport","--reportformat","json","--units","b","--nosuffix","--configreport","vg","-o","vg_name,vg_uuid,vg_size,vg_free","--configreport","lv","-o","lv_uuid,lv_name,lv_full_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags,lv_attr,vg_name,data_percent,metadata_percent,pool_lv","--configreport","pv","-o,","--configreport","pvseg","-o,","--configreport","seg","-o,"]}
not found
{"level":"error","ts":"2024-01-14T12:52:45Z","msg":"volume group not found","volume_group":"instancestore","error":"not found","stacktrace":"github.com/topolvm/topolvm/pkg/lvmd/cmd.subMain\n\t/workdir/pkg/lvmd/cmd/root.go:70\ngithub.com/topolvm/topolvm/pkg/lvmd/cmd.glob..func2\n\t/workdir/pkg/lvmd/cmd/root.go:45\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/topolvm/topolvm/pkg/lvmd/cmd.Execute\n\t/workdir/pkg/lvmd/cmd/root.go:130\nmain.main\n\t/workdir/pkg/hypertopolvm/main.go:38\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
Error: not found
```

values from helm chart
```
    cert-manager:
      enabled: false
    scheduler:
      enabled: false
      type: Deployment
      service:
        type: ClusterIP
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - topolvm
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - scheduler
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: NotIn
                    values:
                      - system
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: topolvm
              app.kubernetes.io/component: scheduler
          matchLabelKeys:
            - pod-template-hash
      priorityClassName: "system-cluster-critical"
    lvmd:
     
      deviceClasses:
        - name: default
          volume-group: instancestore
          default: true
          spare-gb: 10
      priorityClassName: system-node-critical
      tolerations:
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: topolvm.github.io/agent-not-ready
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: karpenter.k8s.aws/instance-local-nvme
                    operator: Exists
    node:
      priorityClassName: system-node-critical
      tolerations:
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: topolvm.github.io/agent-not-ready
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: karpenter.k8s.aws/instance-local-nvme
                    operator: Exists
    controller:
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      affinity: |
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - topolvm
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - controller
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: NotIn
                    values:
                      - system
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: topolvm
              app.kubernetes.io/component: controller
          matchLabelKeys:
            - pod-template-hash
      priorityClassName: "system-cluster-critical"
    storageClasses:
      - name: nvme-xfs # Defines name of storage class.
        storageClass:
          # Supported filesystems are: ext4, xfs, and btrfs.
          fsType: xfs
          # reclaimPolicy
          reclaimPolicy: Delete
          # Additional annotations
          annotations: {}
          # Default storage class for dynamic volume provisioning
          # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
          isDefaultClass: false
          # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
          volumeBindingMode: WaitForFirstConsumer
          # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
          allowVolumeExpansion: true
          additionalParameters:
            "topolvm.io/device-class": "default"
          # mount options
          mountOptions: []
          allowedTopologies:
            - matchLabelExpressions:
                - key: karpenter.k8s.aws/instance-local-nvme
                  operator: Exists

```
