### DISCUSSION TITLE
Insufficient topolvm.io/capacity, need help

### DISCUSSION THREAD

**Discussion by mkostelcev** [topolvm/topolvm#841] [Q&A] [answered]
Hello!

I have a kubernetes cluster on virtual-machines under Ubuntu 20.04.6 with 15 nodes, 10 of which have taints and 5 not have. 

Not so long ago, the cluster was updated from kubernetes version 1.23.5 to version 1.24.13 due to stable-support of Storage Capacity Tracking. And updated TopoLVM to latest version. Chart: 14.0.0, 

I'll installed topolvm using helm chart. I turned on storage capacity tracking and turned off scheduler. The current Values look like this:

```yaml
cert-manager:
  enabled: false
scheduler:
  enabled: false
controller:
  prometheus:
    podMonitor:
      enabled: false
  replicaCount: 3
  storageCapacityTracking:
    enabled: true
lvmd:
  tolerations:
  - key: node-role.kubernetes.io/runner
    effect: NoSchedule
  - key: node-role.kubernetes.io/s3
    effect: NoSchedule
  affinity: {}
  deviceClasses:
  - default: true
    name: ssd
    spare-gb: 1
    volume-group: vglocalpv
  managed: true
  socketName: /run/topolvm/lvmd.sock
node:
  tolerations:
  - key: node-role.kubernetes.io/runner
    effect: NoSchedule
  - key: node-role.kubernetes.io/s3
    effect: NoSchedule
  lvmdEmbedded: false
  metrics:
    enabled: false
  prometheus:
    podMonitor:
      enabled: false
storageClasses:
- name: gp2
  storageClass:
    allowVolumeExpansion: true
    fsType: ext4
    isDefaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
- name: topolvm
  storageClass:
    allowVolumeExpansion: true
    fsType: ext4
    isDefaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
- name: topolvm-tmp
  storageClass:
    allowVolumeExpansion: true
    fsType: xfs
    isDefaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
snapshot:
  enabled: false
```

Problem: I have an error when I deploy pod with TopoLVM's storage-classes (any). `5 Insufficient topolvm.io/capacity.`. 

The capacity on the nodes corresponds to or exceeds the requested size. 

Neither kube-scheduler nor topolvm-controller report any errors, but they also do not see new pvc, they are in the Pending status.

Please help me fix it :)

**Comment by daichimukai** [comment]
Hi @mkostelcev,

When the storage capacity tracking is in use, the external-provisioner maintains nodes' capacity information in the CSIStorageCapacity resources. Could you look for the capacity field therein, and check if these are correct values?

For example, I found the following resource in my test cluster. It claims that there is 20GiB available capacity in the node `topolvm-e2e-worker` for the `topolvm-provisioner-thin` SC.

```
apiVersion: storage.k8s.io/v1
capacity: 20Gi
kind: CSIStorageCapacity
metadata:
  creationTimestamp: "2024-02-14T08:02:30Z"
  generateName: csisc-
  labels:
    csi.storage.k8s.io/drivername: topolvm.io
    csi.storage.k8s.io/managed-by: external-provisioner
  name: csisc-7wklg
  namespace: topolvm-system
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: topolvm-controller
      uid: 6b13dcdf-9f85-4346-9d6b-1c56575f0dc6
  resourceVersion: "6804"
  uid: 847af7da-25fe-4e3a-be9a-4bace5d17e38
nodeTopology:
  matchLabels:
    topology.topolvm.io/node: topolvm-e2e-worker
storageClassName: topolvm-provisioner-thin
```

Thanks.

**Comment by daichimukai** [comment]
As another possibility, you may need to reconfigure the settings of kube-scheduler. Once you have started to use topolvm-scheduler, you might have configured kube-scheduler to ask topolvm-scheduler on Pod scheduling. This should be reverted.

cf. https://github.com/topolvm/topolvm/blob/1b19381babdddd94a3f96cd0b2bed861ffead95f/docs/advanced-setup.md#using-topolvm-scheduler

**Comment by mkostelcev** [comment]
@daichimukai 

Hello again, sorry for my long away =)

scheduler has been rolled back to default settings (without custom config setting), but this not helped for me

my CSI-SC list:

```
k get CSIStorageCapacities -n topolvm-system
NAME          CREATED AT
csisc-42t2r   2024-03-15T15:05:12Z
csisc-4d9gk   2024-02-08T10:46:28Z
csisc-4t27q   2024-02-08T10:18:26Z
csisc-4tx4p   2024-03-15T15:05:21Z
csisc-4ztrj   2024-02-08T10:18:38Z
csisc-6jbrz   2024-02-08T10:46:28Z
csisc-6t8pv   2024-02-08T10:46:28Z
csisc-6vfqd   2024-02-13T09:13:28Z
csisc-7wklq   2024-03-15T15:05:16Z
csisc-7xcrt   2024-02-13T09:13:22Z
csisc-7zm8k   2024-02-13T09:13:22Z
csisc-8l7v4   2024-03-15T15:05:07Z
csisc-8wpwr   2024-02-08T10:18:39Z
csisc-9nmvv   2024-02-08T10:18:37Z
csisc-9rwhs   2024-02-12T13:03:32Z
csisc-9vgwr   2024-02-13T09:13:25Z
csisc-bq2c8   2024-03-15T15:05:07Z
csisc-bw58j   2024-02-08T10:18:51Z
csisc-c726m   2024-02-13T09:13:24Z
csisc-cvw7z   2024-03-15T15:05:09Z
csisc-cwhqq   2024-02-08T10:18:49Z
csisc-czl4w   2024-02-08T10:18:43Z
csisc-djs4t   2024-02-12T13:03:28Z
csisc-dphtk   2024-03-15T15:05:20Z
csisc-drdpb   2024-02-08T10:18:53Z
csisc-drhbh   2024-02-08T10:19:13Z
csisc-fcvn6   2024-03-15T15:05:07Z
csisc-fqhwn   2024-02-08T10:19:20Z
csisc-g8xwb   2024-02-08T10:18:50Z
csisc-gmct7   2024-02-08T10:19:14Z
csisc-hmh2f   2024-02-13T09:13:22Z
csisc-hvfng   2024-02-08T10:18:26Z
csisc-j56qz   2024-02-12T13:03:31Z
csisc-k28jh   2024-02-08T10:18:26Z
csisc-k7xj5   2024-02-08T10:19:19Z
csisc-k9vdv   2024-02-08T10:18:44Z
csisc-kcjqq   2024-02-08T10:19:21Z
csisc-kqtjd   2024-03-15T15:05:07Z
csisc-lhr2t   2024-02-12T13:03:27Z
csisc-ms2vg   2024-02-08T10:18:52Z
csisc-msc8s   2024-02-08T10:19:15Z
csisc-n6ls2   2024-02-13T09:13:27Z
csisc-nrn65   2024-03-15T15:05:13Z
csisc-nw5vc   2024-03-15T15:05:17Z
csisc-nxrtz   2024-02-08T10:19:12Z
csisc-qm5gh   2024-02-08T10:18:54Z
csisc-rxdt7   2024-03-15T15:05:08Z
csisc-tcl75   2024-02-08T10:19:10Z
csisc-th66k   2024-02-13T09:13:23Z
csisc-vh2xl   2024-02-12T13:03:30Z
csisc-wvfwg   2024-02-13T09:13:22Z
csisc-wvzpm   2024-02-08T10:18:45Z
csisc-xqbpx   2024-02-08T10:19:11Z
csisc-zdc8b   2024-02-13T09:13:22Z
csisc-zp6g4   2024-02-13T09:13:26Z
csisc-zrxcg   2024-02-12T13:03:29Z
```

spec for someone
```
apiVersion: storage.k8s.io/v1
capacity: 110584Mi
kind: CSIStorageCapacity
metadata:
  creationTimestamp: "2024-02-12T13:03:29Z"
  generateName: csisc-
  labels:
    csi.storage.k8s.io/drivername: topolvm.io
    csi.storage.k8s.io/managed-by: external-provisioner
  name: csisc-zrxcg
  namespace: topolvm-system
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: topolvm-controller
    uid: 9e39e178-778b-48c7-a8ea-98b1bbdabda1
  resourceVersion: "344903709"
  uid: 536dc1e4-071a-49f8-89a3-a06a28d8b391
nodeTopology:
  matchLabels:
    topology.topolvm.io/node: conplane-w01
storageClassName: topolvm-tmp
```

What I should check here/else?

**Comment by mkostelcev** [comment]
I add some info about my steps:

1. Spec for test

<details>
<summary> Click for see SPEC </summary>

```
kind: Pod
apiVersion: v1
metadata:
  name: darwin
  namespace: default
spec:
  containers:
    - name: generic-volume-mount
      image: nginx
      volumeMounts:
      - mountPath: "/var/log"
        name: darwin-generic-volume
  volumes:
    - name: darwin-generic-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: darwin-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "topolvm-tmp"
            resources:
              requests:
                storage: 1Gi
```

</details>

All nodes have >10Gi free space 

2. `k describe pod darwin`

<details>
<summary> DESCRIBE POD RESULT </summary>

```
Name:             darwin
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           <none>
Annotations:      capacity.topolvm.io/00default: 1073741824
Status:           Pending
IP:
IPs:              <none>
Containers:
  generic-volume-mount:
    Image:      nginx
    Port:       <none>
    Host Port:  <none>
    Limits:
      topolvm.io/capacity:  1
    Requests:
      topolvm.io/capacity:  1
    Environment:            <none>
    Mounts:
      /var/log from darwin-generic-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-k42wl (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  darwin-generic-volume:
    Type:          EphemeralVolume (an inline specification for a volume that gets created and deleted with the pod)
    StorageClass:  topolvm-tmp
    Volume:
    Labels:            type=darwin-volume
    Annotations:       <none>
    Capacity:
    Access Modes:
    VolumeMode:    Filesystem
  kube-api-access-k42wl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  19m                  default-scheduler  0/18 nodes are available: 18 waiting for ephemeral volume controller to create the persistentvolumeclaim "darwin-darwin-generic-volume". preemption: 0/18 nodes are available: 18 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  8m52s (x2 over 13m)  default-scheduler  0/18 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/ingress-nginx: }, 2 node(s) had untolerated taint {node-role.kubernetes.io/runner: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/monitoring: }, 5 Insufficient topolvm.io/capacity, 4 node(s) had untolerated taint {node-role.kubernetes.io/s3: }. preemption: 0/18 nodes are available: 15 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod.
```

</details>

-> `...5 Insufficient topolvm.io/capacity...`, but nodes have capacity...

3. `k describe pvc`

<details>
<summary> DESCRIBE PVC RESULT </summary>

```
Name:          darwin-darwin-generic-volume
Namespace:     default
StorageClass:  topolvm-tmp
Status:        Pending
Volume:
Labels:        type=darwin-volume
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection topolvm.io/pvc]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       darwin
Events:
  Type    Reason               Age                 From                         Message
  ----    ------               ----                ----                         -------
  Normal  WaitForPodScheduled  86s (x82 over 21m)  persistentvolume-controller  waiting for pod darwin to be scheduled
```

</details>

pv is not creating on this step...
where and what I should check else?

**Reply by daichimukai** [reply]
Hi @mkostelcev,

>   Warning  FailedScheduling  8m52s (x2 over 13m)  default-scheduler  0/18 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/ingress-nginx: }, 2 node(s) had untolerated taint {node-role.kubernetes.io/runner: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/monitoring: }, 5 Insufficient topolvm.io/capacity, 4 node(s) had untolerated taint {node-role.kubernetes.io/s3: }. preemption: 0/18 nodes are available: 15 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod.

It looks to me that all nodes with enough storage capacity have untolerated taints. Which nodes do you consider to be schedulable? Please check taints and associated CSIStorageCapacity resources for that nodes.

**Reply by mkostelcev** [reply]
w01:

```
Name:         csisc-zrxcg
Namespace:    topolvm-system
Labels:       csi.storage.k8s.io/drivername=topolvm.io
              csi.storage.k8s.io/managed-by=external-provisioner
Annotations:  <none>
API Version:  storage.k8s.io/v1
Capacity:     110584Mi
Kind:         CSIStorageCapacity
Metadata:
  Creation Timestamp:  2024-02-12T13:03:29Z
  Generate Name:       csisc-
  Owner References:
    API Version:     apps/v1
    Controller:      true
    Kind:            Deployment
    Name:            topolvm-controller
    UID:             9e39e178-778b-48c7-a8ea-98b1bbdabda1
  Resource Version:  344903709
  UID:               536dc1e4-071a-49f8-89a3-a06a28d8b391
Node Topology:
  Match Labels:
    topology.topolvm.io/node:  conplane-w01
Storage Class Name:            topolvm-tmp
Events:                        <none>
```

w02:
```
Name:         csisc-4d9gk
Namespace:    topolvm-system
Labels:       csi.storage.k8s.io/drivername=topolvm.io
              csi.storage.k8s.io/managed-by=external-provisioner
Annotations:  <none>
API Version:  storage.k8s.io/v1
Capacity:     110584Mi
Kind:         CSIStorageCapacity
Metadata:
  Creation Timestamp:  2024-02-08T10:46:28Z
  Generate Name:       csisc-
  Owner References:
    API Version:     apps/v1
    Controller:      true
    Kind:            Deployment
    Name:            topolvm-controller
    UID:             9e39e178-778b-48c7-a8ea-98b1bbdabda1
  Resource Version:  319972416
  UID:               bd4bf591-9f0d-46de-ad86-9ea993dbbc2d
Node Topology:
  Match Labels:
    topology.topolvm.io/node:  conplane-w02
Storage Class Name:            topolvm-tmp
Events:                        <none>
```

w03:

```
Name:         csisc-kcjqq
Namespace:    topolvm-system
Labels:       csi.storage.k8s.io/drivername=topolvm.io
              csi.storage.k8s.io/managed-by=external-provisioner
Annotations:  <none>
API Version:  storage.k8s.io/v1
Capacity:     108536Mi
Kind:         CSIStorageCapacity
Metadata:
  Creation Timestamp:  2024-02-08T10:19:21Z
  Generate Name:       csisc-
  Owner References:
    API Version:     apps/v1
    Controller:      true
    Kind:            Deployment
    Name:            topolvm-controller
    UID:             9e39e178-778b-48c7-a8ea-98b1bbdabda1
  Resource Version:  344903696
  UID:               6fbd818a-5ff1-4567-9ff7-4e8f101d0300
Node Topology:
  Match Labels:
    topology.topolvm.io/node:  conplane-w03
Storage Class Name:            topolvm-tmp
Events:                        <none>
```

w04:
```
Name:         csisc-8wpwr
Namespace:    topolvm-system
Labels:       csi.storage.k8s.io/drivername=topolvm.io
              csi.storage.k8s.io/managed-by=external-provisioner
Annotations:  <none>
API Version:  storage.k8s.io/v1
Capacity:     57336Mi
Kind:         CSIStorageCapacity
Metadata:
  Creation Timestamp:  2024-02-08T10:18:39Z
  Generate Name:       csisc-
  Owner References:
    API Version:     apps/v1
    Controller:      true
    Kind:            Deployment
    Name:            topolvm-controller
    UID:             9e39e178-778b-48c7-a8ea-98b1bbdabda1
  Resource Version:  319954825
  UID:               0906f550-d1bb-4133-a110-02d8f3f4165d
Node Topology:
  Match Labels:
    topology.topolvm.io/node:  conplane-w04
Storage Class Name:            topolvm-tmp
Events:                        <none>
```

w05:
```
Name:         csisc-9rwhs
Namespace:    topolvm-system
Labels:       csi.storage.k8s.io/drivername=topolvm.io
              csi.storage.k8s.io/managed-by=external-provisioner
Annotations:  <none>
API Version:  storage.k8s.io/v1
Capacity:     108536Mi
Kind:         CSIStorageCapacity
Metadata:
  Creation Timestamp:  2024-02-12T13:03:32Z
  Generate Name:       csisc-
  Owner References:
    API Version:     apps/v1
    Controller:      true
    Kind:            Deployment
    Name:            topolvm-controller
    UID:             9e39e178-778b-48c7-a8ea-98b1bbdabda1
  Resource Version:  322522181
  UID:               e761636a-09a1-47db-8d32-bebdcbb93ee5
Node Topology:
  Match Labels:
    topology.topolvm.io/node:  conplane-w05
Storage Class Name:            topolvm-tmp
Events:                        <none>
```

Other nodes has taints, I know about it, but these nodes are not and I expect to see pv on them

**Comment by mkostelcev** [comment, marked as answer]
Problem resolved. Thanks for issue https://github.com/topolvm/topolvm/issues/353

How to resolve:

1. I noticed that when applying pod, it has an annotation "capacity.topolvm.io/00default: xxxxx". This means that someone interferes with the specification of the hearth when it is deployed. According to the k8s architecture, an operator or mutation webhook can interfere.
2. I checked that the helm chart param `webhook.podMutatiingWebhook` is set to `false`. This parameter was indeed set to `false`.
3. Making sure, that the webhook is exists:

`k get MutatingWebhookConfiguration` 
```
NAME                    WEBHOOKS   AGE
cert-manager-webhook    1          462d
topolvm-hook            2          460d
```

`k get -o yaml MutatingWebhookConfiguration topolvm-hook
apiVersion: admissionregistration.k8s.io/v1`

(some fields are hidden)
```
kind: MutatingWebhookConfiguration
metadata:
  ...
  name: topolvm-hook
  ...
webhooks:
- ...
  name: pvc-hook.topolvm.io
  namespaceSelector:
    matchExpressions:
    - key: topolvm.io/webhook
      operator: NotIn
      values:
      - ignore
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
...
- ...
  name: pod-hook.topolvm.io
  namespaceSelector:
    matchExpressions:
    - key: topolvm.io/webhook
      operator: NotIn
      values:
      - ignore
 ...
```

But the webhook with name `pod-hook.topolvm.io` is STILL here.

After I deleted them manually - all works as expected!

@daichimukai Thanks for trying to help.  And attention to this message for test removing webhook in case switching from scheduler-extender to StorageCapacityTracking, thank you!
