### DISCUSSION TITLE
topolvm node capacity not updated with embedded lvmd

### DISCUSSION THREAD

**Discussion by jurim76** [topolvm/topolvm#842] [Q&A]
According to this [article](https://github.com/topolvm/topolvm/blob/main/docs/limitations.md#capacity-aware-scheduling-may-go-wrong)
"Node storage capacity annotation is not updated in TopoLVM's extended scheduler"

Some reason for that? Or only embedded lvmd is affected?
I'm expecting dynamic capacity update for production environment (aka without daemonset restart)

Afer topolvm helm chart installation, node annotation shows zero capacity
```yaml
  annotations:
    capacity.topolvm.cybozu.com/00default: "0"
```
After topolvm-node ds restart (kubectl -n topolvm-system rollout restart ds topolvm-node), node capacity annotation is correct
```yaml
  annotations:
    capacity.topolvm.cybozu.com/00default: "309233451008"
    capacity.topolvm.cybozu.com/encryptedssd: "309233451008"
```

My settings:

k8s version: 1.27.10
topolvm chart version: 14.0.0

chart's values.custom.yaml

```yaml
useLegacy: true

scheduler:
  enabled: true
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "200m"

lvmd:
  managed: false
  deviceClasses:
  - name: encryptedssd
    volume-group: topolvm-vg
    default: true
    spare-gb: 2

storageClasses:
- name: topolvm-ext4
  storageClass:
    fsType: ext4
    isDefaultClass: true
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    additionalParameters:
      "topolvm.cybozu.com/device-class": "encryptedssd"

node:
  lvmdEmbedded: true
  lvmdSocket: /run/topolvm/lvmd.sock
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 500m
  nodeSelector:
    topolvm: "true"

controller:
  storageCapacityTracking:
    enabled: false
  replicaCount: 2
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  nodeSelector:
    tooling: "true"

webhook:
  podMutatingWebhook:
    enabled: true
    ```
