### DISCUSSION TITLE
Add custom annotation support for CRD

### DISCUSSION THREAD

**Discussion by jurim76** [topolvm/topolvm#954] [Q&A] [answered]
Perpahs it's a good idea to add custom annotation support for CRD, for example I need to add `helm.sh/resource-policy: keep` annotation to prevent helm from CRD uninstalling (and keep LVs safe)

Something like this
```
 {{ if not .Values.useLegacy }}                                                                                   
  ---                                                                                                                                                                    
  apiVersion: apiextensions.k8s.io/v1                                                                                                                                    
  kind: CustomResourceDefinition                                                                                                                                         
  metadata:                                                                                                                                                              
    annotations:                                                                                                                                                         
      controller-gen.kubebuilder.io/version: v0.15.0
 {{- if .Values.customAnnotation }}
 {{ toYaml .Values.customAnnotations | nindent 4 }}
 {{ -end }}                                                                                                                      
    name: logicalvolumes.topolvm.io 
  ```
What's your thoughts about this?

UPD
CRD is getting deleted even with "helm.sh/resource-policy: keep" annotation
```
> flux get hr topolvm
NAME    REVISION        SUSPENDED       READY   MESSAGE                                                                                     
topolvm 15.2.0-b0+1     False           True    Helm install succeeded for release topolvm-system/topolvm.v1 with chart topolvm@15.2.0-b0+1

> kubectl get crd logicalvolumes.topolvm.cybozu.com -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
    helm.sh/resource-policy: keep
    ---
> flux delete hr topolvm
Are you sure you want to delete this helmrelease: y
► deleting helmrelease topolvm in flux-system namespace
✔ helmrelease deleted

>  kubectl describe crd logicalvolumes.topolvm.cybozu.com
Status:
  Accepted Names:
    Kind:       LogicalVolume
    List Kind:  LogicalVolumeList
    Plural:     logicalvolumes
    Singular:   logicalvolume
  Conditions:
    Last Transition Time:  2024-08-19T08:04:45Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2024-08-19T08:04:45Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2024-08-19T08:08:19Z
    Message:               CustomResource deletion is in progress
    Reason:                InstanceDeletionInProgress
    Status:                True
    Type:                  Terminating <----
  Stored Versions:
    v1
```

UPD
CRD is not deleted with flux HelmRelease uninstall policy
```
  uninstall:                                                                                                                                                             
    deletionPropagation: "orphan"
```

**Comment by daichimukai** [comment, marked as answer]
Hi @jurim76,

> Perpahs it's a good idea to add custom annotation support for CRD, for example I need to add helm.sh/resource-policy: keep annotation to prevent helm from CRD uninstalling (and keep LVs safe)

Agreed. Although the field name `customAnnotations` in values.yaml might needs some improvement, I think we would accept your suggestion.

**Reply by jurim76** [reply]
Hi @daichimukai 
Thank you for your answer, but I'm not sure how custom annotations will be useful in case of CRD currently.
Perhaps helm labels should be added to CRD template in combination with pre-defined "helm.sh/resource-policy: keep" annotation?

**Reply by daichimukai** [reply]
I'm not sure, but at least when I tried `helm uninstall` with `helm.sh/resource-policy: keep` annotation on the CRD, it worked as expected.

**Reply by jurim76** [reply]
Another example, that I looked up from cert-manager chart
```
  kind: CustomResourceDefinition                                                                                                                                         
  metadata:                                                                                                                                                              
    name: certificaterequests.cert-manager.io                                                                                                                            
    # START annotations {{- if .Values.crds.keep }}                                                                                                                      
    annotations:                                                                                                                                                         
      helm.sh/resource-policy: keep                                                                                                                                      
    # END annotations {{- end }}                                                                                                                                         
    labels:                                                                                                                                                              
      app: '{{ template "cert-manager.name" . }}'                                                                                                                        
      app.kubernetes.io/name: '{{ template "cert-manager.name" . }}'                                                                                                     
      app.kubernetes.io/instance: '{{ .Release.Name }}'                                                                                                                  
      # Generated labels {{- include "labels" . | nindent 4 }} 
     ```
