### ISSUE TITLE
Support for custom topology key

### ISSUE THREAD

**Issue by vladimirfx** [topolvm/topolvm#1010]
**What should the feature do:**

Please add support for setting custom topology keys to improve scheduling on different hardware (NVME, RAID, etc.). Related discussion: https://github.com/topolvm/topolvm/discussions/712

**What is use case behind this feature:**

Sample topology to assign mirrored LVs to nodes with 2+ physical volumes:

```yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid1
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: common
  topolvm.io/lvcreate-option-class: raid1
provisioner: topolvm.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: feature.node.kubernetes.io/lvm.raid1.present
    values:
    - true
```

**Comment by llamerada-jp** [comment]
TopoLVM can handle multiple hardware devices by assigning a device class to each hardware device. Pods are only placed on nodes that provide the device class specified by the StorageClass specified by PVC. Examples are shown below. Is it different from what you want to do?

`lvmd.yaml` file for the node having NVMe:
```yaml
socket-name: /run/topolvm/lvmd.sock
device-classes:
  - name: nvme1
    volume-group: nvme-vg
    spare-gb: 10
    default: true
```

`lvmd.yaml` file for the node having RAID:
```yaml
socket-name: /run/topolvm/lvmd.sock
device-classes:
  - name: raid1-1
    volume-group: raid-vg
    lvcreate-options:
      - --type=raid1
```

SC for providing nvme nodes
```yaml
kind: StorageClass
metadata:
  name: nvme1
parameters:
  topolvm.io/device-class: nvme1
<snip>
```

for providing RAID
```yaml
kind: StorageClass
metadata:
  name: raid1-1
parameters:
  topolvm.io/device-class: raid1-1
<snip>
```

ref: https://github.com/topolvm/topolvm/blob/main/docs/lvmd.md#config-file-format

**Comment by vladimirfx** [comment]
This approach assumes sticking to VG deployment because the device class maps to VG one-to-one. In our deployments, we partition device classes by rotational (SSD) factor only. LVM options are too flexible to form distinct device classes (and VGs). So we successfully use common VGs for `linear`, `raid1`, `thinpool` volumes without any issues. It is unreal for us to have all those use cases on distinct VGs with their PVs.

So associating some special `lvcreate-option-class`es with capable hardware using topology keys is an elegant way to achieve maximum flexibility on reasonable hardware.

**Comment by llamerada-jp** [comment]
`lvcreate-options` may not have been necessary, so please forget about it. In the example below, it is possible to provide multiple StorageClasses with a common VG. I would like you to explain in detail what is wrong with this in your environment, using a minimal sample or something similar.

```
socket-name: /run/topolvm/lvmd.sock
device-classes:
  - name: rotational
    volume-group: vg
lvcreate-option-classes:
  - name: raid1
    options:
      - some options
  - name: rotational-thin
    volume-group: vg
    type: thin
    thin-pool:
        name: pool0
        overprovision-ratio: 50.0
```

```
kind: StorageClass
metadata:
  name: liner
parameters:
  topolvm.io/device-class: rotational
---
kind: StorageClass
metadata:
  name: raid1
parameters:
  topolvm.io/device-class: rotational
  topolvm.io/lvcreate-option-class: raid1
---
kind: StorageClass
metadata:
  name: thinpool
parameters:
  topolvm.io/device-class: rotational-thin
```
