### ISSUE TITLE
Pod with `nodeName` leads to permanently unbound PVC

### ISSUE THREAD

**Issue by Javex** [topolvm/topolvm#1023]
**Describe the bug**
When I schedule a pod on a particular node with `nodeName` explicitly, the PVC is never bound. When I remove the restriction, the PV & LV are created and the pod is started. Ironically, the scheduler picked the exact node that I previously had in the `nodeName` so I know for sure that the node works (the LV got created on the host).

I'm not sure if this _is_ a bug or if this isn't supposed to work but I couldn't find any docs or open issues for it. Here's my reproducer:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: data-pod
  namespace: default
spec:
  containers:
    - name: data-pod
      image: debian:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName:  data
  nodeName: node1
  restartPolicy: Never
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
spec:
  storageClassName: topolvm-provisioner-thin
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Mi"
```

TopoLVM itself is installed via helm using the following `values.yaml`

```yaml
controller:
  args:
    - --zap-log-level
    - debug
lvmd:
  deviceClasses:
    - name: ssd
      volume-group: topovg
      default: true
      type: thin
      spare-gb: 5
      thin-pool:
        name: topothin
        overprovision-ratio: 5.0


storageClasses:
  - name: topolvm-provisioner-thin
    storageClass:
      fsType: ext4
      reclaimPolicy: Retain
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        '{{ include "topolvm.pluginName" . }}/device-class': "ssd"
      mountOptions:
        - discard
```

**Environments**
- Version: Helm chart `15.5.2`
- OS: Linux 6.13.3

**To Reproduce**
1. Install via helm using values above
2. Format PV, VG & thin pool (just use default options)
3. Create Pod & PVC (in any order)
4. Pod is never scheduled.

The only error indicating the issue will be that the Pod has this event:
```
Unable to attach or mount volumes: unmounted volumes=[data-volume], unattached volumes=[], failed to process volumes=[data-volume]: error processing PVC default/data: PVC is not bound
```
The PVC stays in "Pending", the PV is not created and neither is an LVM LV.

Remove the `nodeName` and it works.

**Expected behavior**
If the targeted node is valid for scheduling, TopoLVM should create the PV there.
