### ISSUE TITLE
Support hosts without lvm CLI preinstalled

### ISSUE THREAD

**Issue by vholer** [topolvm/topolvm#1042]
**What should the feature do:**

There are commonly used host OS images (e.g., AWS Bottlerocket), which don't have lvm CLI preinstalled, trying to run those from node container via `nsenter` fails. It would be nice, if topolvm doesn't use an nsenter to trigger CLI, but can e.g. have them preinstalled in the container.

Related question https://github.com/topolvm/topolvm/issues/821

**What is use case behind this feature:**

Support host OS images with a limited set of components preinstalled.

**Comment by ushitora-anqou** [comment]
Unfortunately, using LVM in a container without nsenter isn't feasible because it's known that there's no safe way to use LVM both inside the container and on the host at the same time. When we try to do so LVM metadata can be corrupted.

cf. https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-common-issues/#symptoms_9

**Comment by ushitora-anqou** [comment]
Ah, got it. We may be able to avoid using nsenter in such a situation. I'll chat with my colleagues to see if there are any other concerns.

By the way, just out of curiosity, can you manage LVM without installing the LVM commands on the host? It seems like you have to run all the LVM commands through the containers, which feels a bit tedious.

**Comment by vholer** [comment]
Nice, if it's hard to convince your colleagues, it might help that I could contribute this feature (add lvm tools into an image, modify CSI to **conditionally** use local tools instead of nsenter behind a flag - by default disabled with explanation that it could be dangerous in majority of environments,...).

> By the way, just out of curiosity, can you manage LVM without installing the LVM commands on the host? It seems like you have to run all the LVM commands through the containers, which feels a bit tedious.

ATM, I'm not able to use TopoLVM on these restricted hosts (with AWS Bottlerocket OS), but I have following stub which at least prepare LVM pool as part of **topolvm-node** init container. Yes, the commands are ran within a container, it doesn't matter at the end if it's this way, some cloud-init bootstrap script.

E.g.,

```
  initContainers:
  - command:
    - /bin/sh
    - -exc
    - |
      apk add --update --no-cache lvm2

      DEVICE=/dev/nvme2n1
      pvs "${DEVICE}"  || pvcreate "${DEVICE}"
      vgs vg-topolvm || vgcreate vg-topolvm "${DEVICE}"
      lvs vg-topolvm/topolvm_thin || lvcreate -l 100%FREE --chunksize 64 -T -A n -n topolvm_thin vg-topolvm
    image: docker.io/alpine:3.21
    imagePullPolicy: IfNotPresent
    name: create-vg
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev
      name: devices-dir
```

So, this works, what doesn't work is actual use, since there are no LVM tools within topolvm image and also topolvm tries to nsenter. But, if I install `lvm2` package into the TopoLVM image and try to manage LVM volumes there, it works as well.

**Comment by ushitora-anqou** [comment]
Thank you for your reply. It's interesting.

I discussed this issue with my team, and one concern we've found is that the version of the LVM commands that the host expects may be different from the one in the container. So, users probably can't use TopoLVM's default Docker image if they play it safe, and they have to build their own one instead. But this shouldn't be a significant problem.

I'll start to implement to resolve this issue.

**Comment by remidinishanth** [comment]
@vholer How are you deploying K8s onto host, is it via container? Which tool are you using? I faced similar issue with https://github.com/gravitational/planet

**Comment by vholer** [comment]
@remidinishanth We are using AWS EKS with Bottlerocket OS, which is a limited system focused only on running Kubernetes without common tools (like LVM). Kubelet is not running in container there.

**Comment by ushitora-anqou** [comment]
We've merged #1045, which can be used to address this issue. If you set the new `lvm-command-prefix` option to an empty array (`[]`), nsenter will no longer be used when invoking LVM commands. For a working example, see the following: https://github.com/topolvm/topolvm/compare/ed1cc9681d08c66e5bee3132588593f19c90f273..a7b8f042c9743c610bdc7b2ba4e59fd20e6fbdef

Please note, however, that running LVM without nsenter is possible but not recommended (see https://github.com/topolvm/topolvm/pull/1045#issuecomment-3035219830). Users should enable this setting if they're sure they understand the consequences.

**Comment by vholer** [comment]
@ushitora-anqou Thank you, it's working for me at the end, I really appreaciate it! I only found and issue with Helm chart not indenting properly the `lvmd.additionalLVMDYamlContent` while creating  the lvmd configmap. Related PR https://github.com/topolvm/topolvm/pull/1082.

Since there is still no lvm tools preinstalled in the image (would it be feasiable or is this a no go?), I'm using this crazy `lvm-command-prefix` to install the tools on the fly, if anybody would interested:

```
lvmd:
  additionalLVMDYamlContent:
    lvm-command-prefix:
      - '/bin/sh'
      - '-ec'
      - 'command -v lvm >/dev/null || (apt-get update; apt-get install -fy lvm2) >/dev/null 2>&1; exec lvm $@'
      - '--'
```

also, it's important not to forget export env. variable `DM_DISABLE_UDEV=1`.
