### ISSUE TITLE
VolumeID is not found

### ISSUE THREAD

**Issue by magick93** [topolvm/topolvm#1064]
Hello

My statefulset is failing to start. There is this event:

```yaml
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  83s (x12 over 9m37s)  kubelet  MountVolume.SetUp failed for volume "pvc-749f0d3f-ab8c-4011-b6cc-4193e99407e9" : rpc error: code = Unknown desc = VolumeID is not found
```

The `persistentvolume/pvc-749f0d3f-ab8c-4011-b6cc-4193e99407e9` described is:

```yaml
Name:              pvc-749f0d3f-ab8c-4011-b6cc-4193e99407e9
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: topolvm.io
                   volume.kubernetes.io/provisioner-deletion-secret-name: 
                   volume.kubernetes.io/provisioner-deletion-secret-namespace: 
Finalizers:        [external-provisioner.volume.kubernetes.io/finalizer kubernetes.io/pv-protection]
StorageClass:      topolvm-provisioner
Status:            Bound
Claim:             lynx/storage-lynx-0
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          30Gi
Node Affinity:     
  Required Terms:  
    Term 0:        topology.topolvm.io/node in [ho-lynx-tui]
Message:           
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            topolvm.io
    FSType:            xfs
    VolumeHandle:      944696e0-4aad-4d3b-89a5-5c6932e360f3
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=1750812329431-3838-topolvm.io
Events:                <none>
```

And the `persistentvolumeclaim/storage-lynx-0` is:

```yaml
Name:          storage-lynx-0
Namespace:     lynx
StorageClass:  topolvm-provisioner
Status:        Bound
Volume:        pvc-749f0d3f-ab8c-4011-b6cc-4193e99407e9
Labels:        app=lynx
               app.kubernetes.io/instance=ethereum-node
               app.kubernetes.io/name=execution
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: topolvm.io
               volume.kubernetes.io/selected-node: ho-lynx-tui
               volume.kubernetes.io/storage-provisioner: topolvm.io
Finalizers:    [kubernetes.io/pvc-protection topolvm.io/pvc]
Capacity:      30Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       lynx-0
Events:        <none>
```

# Helm `values.yml` used

```yaml
useLegacy: false
scheduler:
  enable: true
node:
  kubeletWorkDirectory: /var/snap/microk8s/common/var/lib/kubelet
lvmd:
  managed: true
  deviceClasses:
    - name: ssd
      volume-group: topolvm
      default: true
      spare-gb: 10

```

# Node logs

See https://gist.github.com/magick93/0b8c363742878f8a0f0169babf1dc2e0

# Versions

- Topolvm Version: v15.5.5
