### ISSUE TITLE
sidecars

### ISSUE THREAD

**Issue by kfox1111** [topolvm/topolvm#196]
**Describe the bug**
The Dockerfile seems to be including the k8s sidecars here:
https://github.com/topolvm/topolvm/blob/master/Dockerfile#L19-L23

But you can use the existing sidecar containers directly in your manifests so they can be cached better when drivers are involved.

**Comment by ymmt2005** [comment]
We intentionally bundle the sidecar images for better integrity.

If a user wants to use other images for sidecars, they can do so by modifying the manifests.
With kustomize, the following patch replaces the csi-provisioner sidecar image.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: topolvm-system
spec:
  containers:
    - name: csi-provisioner
      image: quay.io/k8scsi/csi-provisioner:v1.6.0
```
