### ISSUE TITLE
Duplicate finalizer entry

### ISSUE THREAD

**Issue by dp-42** [topolvm/topolvm#310]
**Describe the bug**
It seems `topolvm` registers an finalizer to newly created PVCs:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  - topolvm.cybozu.com/pvc
  name: pvc-example
  ...
```
Now, when you apply an PVC that **already** contains that finalizer in its YAML definition, the finalizer is added another time, so it looks like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  - topolvm.cybozu.com/pvc
  - topolvm.cybozu.com/pvc
  name: pvc-example
  ...
```
This causes the PVC to get stuck on further operations: For example, if you try to delete the PVC now it will get stuck in the "Terminating" status. As soon as you remove the duplicate finalizer (so that only one remains) the PVC/PV will be deleted immediately.

I don´t think this is intended behavior and therefore I would kindly request a fix.

**Environments**
- Version: K8s 1.19.9
- OS: Ubuntu 20.04

**To Reproduce**
1. Create a PVC that already contains the `topolvm` finalizer (like this: [example-pvc.txt](https://github.com/topolvm/topolvm/files/6453970/example-pvc.txt) )
2. Apply the PVC
3. Check the YAML output of the newly created PVC
4. You should see 2 `topolvm` finalizer entries
4. Remove the PVC
5. You should see that it is stuck in "Terminating"
6. Remove one of the 2 `topolvm` finalizers (`kubectl edit pvc ....`)
7. It should be gone now

**Expected behavior**
Similar to the `kubernetes.io/pvc-protection` I would expect to see only one finalizer registered by `topolvm`. I assume there should be some sort of check before adding the finalizer.

**Additional context**
We discovered this behavior when testing our backup solution. It backups the manifest YAMLs as well as the PV data. When we did multiple backup and restore tests we noticed at some point, that the deletion of the PVCs is stuck.
