### ISSUE TITLE
Support optional VGs in lvmd

### ISSUE THREAD

**Issue by predakanga** [topolvm/topolvm#555]
**What should the feature do:**
At present, lvmd will error at startup if a VG specified by a device class is missing.
I propose that DeviceClass should define an "optional" field.
If this field is set and the referenced VG is missing, LVMd will not error on startup, and will return 0 for capacities, etc, of that DeviceClass.

**What is use case behind this feature:**
When running lvmd as a DaemonSet, there is only a single config shared by all nodes.
If not all nodes have the same storage available (i.e. only some nodes have SSD), you cannot create a device class to target that storage, because it would cause lvmd to error out on all the other nodes.

Heterogenous clusters such as this can be supported by running lvmd on the host with unique config files, so feature parity with the DaemonSet approach would be helpful.

**Open questions:**
- Should lvmd continue checking for VG existence while running?
- Should lvmd start up if all VGs are missing?
- Should lvmd start up if the default VG is missing?

**Comment by toshipp** [comment]
lvmd can be deployed to specific nodes by using nodeSelector.
https://github.com/topolvm/topolvm/blob/main/charts/topolvm/values.yaml#L166
And also, we can deploy multiple lvmd using different configs.
https://github.com/topolvm/topolvm/blob/main/charts/topolvm/values.yaml#L182-L189
Would this solve your problem?

**Comment by predakanga** [comment]
I discovered lvmd.additionalConfigs after creating this issue - it does mostly solve my problem, but I'd prefer that such a workaround wasn't needed.

Also, additionalConfigs doesn't seem to be documented outside of the values file, and the node DaemonSet should probably support affinity, so that you can do something like the following, instead of just nodeSelector:

```yaml
kind: Daemonset
metadata:
  name: topolvm-node
  ...
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: Exists
```

Would you like me to file these as separate issues, or are they already known?
