### ISSUE TITLE
Incorrect default capacity reported on nodes for thin pool

### ISSUE THREAD

**Issue by ppmathis** [topolvm/topolvm#622]
**Describe the bug**
The current TopoLVM release is reporting an incorrect default capacity (`capacity.topolvm.cybozu.com/00default`) on Kubernetes nodes when the default device class is a thin pool and the storage class does not explicitly specify it. The actual capacity that is being reported is the amount of free bytes of the volume group containing the thin pool, but not the amount of available space in the thin pool itself. When deploying a configuration where a thin pool spans 100% of the volume group, this ends up with no PVCs being deployed.

I am not really familiar with the TopoLVM code base, but after a quick glance I think that the capacity annotations are being done in [metrics_exporter.go](https://github.com/topolvm/topolvm/blob/f411453b49ac32e8157809b18602cf0f6d2e10bf/runners/metrics_exporter.go#L232-L241), where first the default annotation is applied followed by device-class specific information. As can be clearly seen, unlike the per-device-class annotation there is no special treatment for thin pools and `WatchResponse.FreeBytes` is always being used.

This message seems to be constructed within [vgservice.go](https://github.com/topolvm/topolvm/blob/main/lvmd/vgservice.go#L137-L215), where `FreeBytes` is always set to the amount of free space in the volume group. As in my case the volume group has no free space and its whole capacity has been dedicated to the thin pool, this ends up with TopoLVM reporting an incorrect default capacity:

```yaml
# This should be the same as ssd-thin, there are no other device classes configured
capacity.topolvm.cybozu.com/00default: 0

# This contains the expected value, due to the special treatment
# within metrics_exporter.go for per-device-class info
capacity.topolvm.cybozu.com/ssd-thin: 397242531840
```

**Environments**
- Version: 0.16.0 installed from Helm Chart 11.0.0
- OS: Debian 11.5 with 5.10.0-19-amd64

**To Reproduce**
1. Create a new volume group named `vg-ssd` on your test system
2. Create a new thin pool on `vg-ssd` named `tp-ssd` and assign 100% of free space to it
3. Deploy TopoLVM using Helm with these value overrides:
```yaml
controller:
  storageCapacityTracking:
    enabled: true

lvmd:
  managed: true
  socketName: /run/topolvm/lvmd.sock
  deviceClasses:
    - name: ssd-thin
      volume-group: vg-ssd
      default: true
      type: thin
      thin-pool:
        name: tp-ssd
        overprovision-ratio: 10.0

scheduler:
  enabled: false

storageClasses:
  - name: topolvm
    storageClass:
      fsType: xfs
      reclaimPolicy: Delete
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true

webhook:
  podMutatingWebhook:
    enabled: false
```
4. Attempt to deploy a PVC on the cluster with the `topolvm` storage class, which has no device class configured and is therefor relying on the default device class `ssd-thin`
5. The PVC remains in `Pending` state and never gets created due to missing capacity, which can also be seen on the Kubernetes node which has the annotation `capacity.topolvm.cybozu.com/00default=0`

**Workaround**
Explicitly specifying the desired device class as part of the storage class with the parameter `topolvm.io/device-class: ssd-thin` fixes the issue, as now `capacity.topolvm.cybozu.com/ssd-thin` instead of `capacity.topolvm.cybozu.com/00default=0` is being checked for scheduling.

**Expected behavior**
Even when there is no specific device class configured on a TopoLVM storage class, the node annotation `capacity.topolvm.cybozu.com/00default=0` should contain the correct capacity for a thin pool configured as the default instead of showing the amount of free bytes on the volume group.

**Comment by daichimukai** [comment]
@suleymanakbas91 @nbalacha 
Could you take on this task?

**Comment by nbalacha** [comment]
> @suleymanakbas91 @nbalacha Could you take on this task?

We will take a look and get back.

**Comment by suleymanakbas91** [comment]
I will work on the fix with the help of @nbalacha.

**Comment by jurim76** [comment]
Have the same issue with latest topolvm chart 14.0.0

k8s version: 1.17.10

values.custom.yaml

```yaml
useLegacy: true

node:
  lvmdEmbedded: true
  lvmdSocket: /run/topolvm/lvmd.sock

scheduler:
  enabled: true

controller:
  storageCapacityTracking:
    enabled: false

lvmd:
  managed: false
  deviceClasses:
    - name: ssd
      volume-group: topolvm-thinpool
      default: true
      type: thin
      thin-pool:
        name: thinpool
        overprovision-ratio: 10.0

storageClasses:
- name: topolvm-thinpool
  storageClass:
    fsType: ext4
    isDefaultClass: true
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    additionalParameters:
      "topolvm.cybozu.com/device-class": "ssd"
```

Configmap topolvm-lvmd-0
```yaml
apiVersion: v1
data:
  lvmd.yaml: "device-classes: \n  - default: true\n    name: ssd\n    thin-pool:\n
    \     name: thinpool\n      overprovision-ratio: 10\n    type: thin\n    volume-group:
    topolvm-thinpool\n"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: topolvm
    meta.helm.sh/release-namespace: topolvm-system
  creationTimestamp: "2024-02-05T14:52:32Z"
  labels:
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/version: 0.26.0
    helm.sh/chart: topolvm-14.0.0
    idx: "0"
  name: topolvm-lvmd-0
  namespace: topolvm-system
  resourceVersion: "41322"
  uid: 3dd0df65-614a-4387-ab0b-04bb1fbab20b
```

Storage class
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: topolvm
    meta.helm.sh/release-namespace: topolvm-system
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-02-05T14:52:32Z"
  labels:
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/version: 0.26.0
    helm.sh/chart: topolvm-14.0.0
  name: topolvm-thinpool
  resourceVersion: "41324"
  uid: 54167893-b23c-4f9f-918c-e07eb7f52f5f
parameters:
  csi.storage.k8s.io/fstype: ext4
  topolvm.cybozu.com/device-class: ssd
provisioner: topolvm.cybozu.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

LVM status on worker node
```
# vgs
  VG         #PV #LV #SN Attr   VSize    VFree  
  topolvm-vg   1   1   0 wz--n- <300.00g 249.96g
# lvs
  LV       VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  thinpool topolvm-vg twi-a-tz-- 50.00g             0.00   10.50  
 ```
 
Topolvm scheduler status is OK, no errors for topolvm-node pods also
Node annotation contains "capacity.topolvm.cybozu.com/00default: 0" only
```
kind: Node
metadata:
  annotations:
    capacity.topolvm.cybozu.com/00default: "0"
    csi.volume.kubernetes.io/nodeid: '{"topolvm.cybozu.com":"infra-pg-worker2011"}'
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
```
