### ISSUE TITLE
[csi-resizer] - VolumeResizeFailed - not enough space

### ISSUE THREAD

**Issue by kfirfer** [topolvm/topolvm#655]
Hello

I'm getting from topolvm-controller the errors:
```
[topolvm-controller-7b98d55b5c-glv8b csi-resizer] 2023-02-10T14:23:53.095451198Z E0210 14:23:53.095374       1 controller.go:286] Error syncing PVC: resize volume "pvc-0ea5d471-e85f-40eb-ba40-fe820cd249e0" by resizer "topolvm.io" failed: rpc error: code = Internal desc = not enough space
asticsearch-data-content-0", UID:"0ea5d471-e85f-40eb-ba40-fe820cd249e0", APIVersion:"v1", ResourceVersion:"7268893", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-0ea5d471-e85f-40eb-ba40-fe820cd249e0" by resizer "topolvm.io" failed: rpc error: code = Internal desc = not enough space
```

When `csi-resizer` trying to resize PVC's (although there are enough space in the nodes), he failed with the above logs
Tried to restart the nodes and recheck the kube-scheduler configurations, nothing special that I could see
I don't know why this happens 
If manually editing the PVC, deleting cascading=false on sts, and delete the PVC&POD, topolvm can successfully create the desired size

### Some info:

K8s version: v1.25.6
Topolvm: helm chart 11.0.1
Topology:  3 K8s control plane nodes

Values overrides of helm chart:
```
podSecurityPolicy:
  create: false

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      annotations:
        resize.topolvm.io/enabled: "true"
      isDefaultClass: true
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters: {}

lvmd:
  deviceClasses:
    - name: ssd
      volume-group: ubuntu-vg
      default: true
      spare-gb: 750

resources:
  lvmd:
    requests:
      memory: "50Mi"
      cpu: "10m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  topolvm_controller:
    requests:
      memory: "150Mi"
      cpu: "10m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  topolvm_scheduler:
    requests:
      memory: "50Mi"
      cpu: "10m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  topolvm_node:
    requests:
      memory: 100Mi
      cpu: 10m
    limits:
      memory: 1Gi
      cpu: 2

snapshot:
  enabled: false
```
  
  
PVC :
```
ubuntu@dev456:~$ kubectl get pvc                                                        
NAME                                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
elasticsearch-data-content-elasticsearch-data-content-0   Bound    pvc-0ea5d471-e85f-40eb-ba40-fe820cd249e0   10Gi       RWO            topolvm-provisioner   12d
```

POD attached PVC:
```
ubuntu@dev456:~$ kubectl get po -o wide | grep content-0
elasticsearch-data-content-0                         1/1     Running   0             6d2h    172.18.137.135    nuc02   <none>           <none>

```
  
LVM:
```
root@nuc02:/# lvs 
  LV                                   VG        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  1c63c646-2742-4d23-b8fc-fa4b25aff99f ubuntu-vg -wi-ao----   3.00g                                                    
  2b4dc494-b7ad-4939-af4d-3deb24db2107 ubuntu-vg -wi-ao----  10.00g                                                    
  37635d34-5d17-479c-8278-ffa9f2ca7b6b ubuntu-vg -wi-ao----  50.00g                                                    
  54e4142e-9ee2-4826-918b-96bcbb448b81 ubuntu-vg -wi-ao----  10.00g                                                    
  7ef03e39-58f7-47b8-ad30-a6cba5621679 ubuntu-vg -wi-ao----   5.00g                                                    
  8192a1d8-c2cb-4bfc-903b-a71342241ea0 ubuntu-vg -wi-ao----  10.00g                                                    
  8d54b083-8833-44a3-b606-989049daf40a ubuntu-vg -wi-ao----  10.00g                                                    
  936b785e-4caa-411b-a665-0e14fc1a35c4 ubuntu-vg -wi-ao----  20.00g                                                    
  b450e48a-af5b-445c-ae02-f9c73bea3465 ubuntu-vg -wi-ao----   1.00g                                                    
  be2f50ec-3ad8-4af7-9fc6-c79059cf19b2 ubuntu-vg -wi-ao----   3.00g                                                    
  c56f3cc4-12af-4882-b939-c62c8d9b20e0 ubuntu-vg -wi-ao----   1.00g                                                    
  cc781525-07e3-49e1-b9c8-d02bdaaaaf96 ubuntu-vg -wi-ao----   5.00g                                                    
  d351273c-6cbe-41df-82e9-db039db982fb ubuntu-vg -wi-ao----  25.00g                                                    
  d6e8cf37-00a9-457c-bb7e-5cbb6544f465 ubuntu-vg -wi-ao----   1.00g                                                    
  dc6b46d9-bca7-459a-a416-6ebc38a69fcb ubuntu-vg -wi-ao----   5.00g                                                    
  e82dbb10-9826-48ba-9e48-141ccddeecc0 ubuntu-vg -wi-ao----   1.00g                                                    
  eec58907-d795-4085-acd5-fb5cfe4ef331 ubuntu-vg -wi-ao----  10.00g                                                    
  f8e4f4e5-e5fe-4929-b278-6fbb52fa1d6f ubuntu-vg -wi-ao----  50.00g                                                    
  ubuntu-lv                            ubuntu-vg -wi-ao---- 150.00g  
  ```

```
root@nuc02:/# vgs
  VG        #PV #LV #SN Attr   VSize    VFree   
  ubuntu-vg   1  19   0 wz--n- <930.01g <560.01g
```

```
root@nuc02:/# vgdisplay
  --- Volume group ---
  VG Name               ubuntu-vg
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  2642
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                19
  Open LV               19
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               <930.01 GiB
  PE Size               4.00 MiB
  Total PE              238082
  Alloc PE / Size       94720 / 370.00 GiB
  Free  PE / Size       143362 / <560.01 GiB
  VG UUID               ie5ene-sdZf-MkLo-S1fc-Tm4Q-xJzw-bXvXY3
  ```
