### ISSUE TITLE
Metrics for logicalvolumes not referenced by pv

### ISSUE THREAD

**Issue by DebakelOrakel** [topolvm/topolvm#710]
**What should the feature do:**

The metric should that (one or more) logicalvolumes are not associated with a pv anymore.

**What is use case behind this feature:**

We have a cluster with `reclaimPolicy: Retain` when the pvc / pv get manually deleted the logicalvolume resides on the node.
Currently we periodically check with `diff -y <(#list of lv) <(#list of pv) to determine if there are any leftovers.

**Comment by satoru-takeuchi** [comment]
> We have a cluster with reclaimPolicy: Retain when the pvc / pv get manually deleted the logicalvolume resides on the node.

Could you tell me how to reproduce your situation step by step?

**Comment by DebakelOrakel** [comment]
My storage class looks like this:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-local
parameters:
  csi.storage.k8s.io/fstype: ext4
  topolvm.cybozu.com/device-class: ssd
provisioner: topolvm.cybozu.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

* Create a deployment with PVC
* Delete PVC, the PV reamins as it should according to the StorageClass
* Delete PV, the Logicalvolume reamains

Do you need some details about the TopoLVM deployment?
