### ISSUE TITLE
csi-registrar/topolvm-node CrashLoopBackOff 15.1.0

### ISSUE THREAD

**Issue by coffee-time-design** [topolvm/topolvm#934]
**Describe the bug**
When I upgrade my dev and test clusters this morning with the new Helm chart 15.1.0, the csi-registrar and topolvm-node containers went into CrashLoopBackOff.
The error I get:
topolvm-node-hqbdt csi-registrar 2024-07-09T12:37:27.401473110+10:00 E0709 02:37:27.399487       1 node_register.go:111] "Health check failed" err="error connecting to node-registrar socket /registration/topolvm.io-reg.sock: context deadline exceeded"

I rolled back both installs to 15.0.0 and the issue goes away.

**Environments**
- Version: v1.29.5+k3s1
- OS: Ubuntu 23.10

**To Reproduce**
Upgrade Helm chart from 15.0.0 to 15.1.0

**Additional context**
I'm no kubernetes expert, so its possible my environment is not ideal.
values file for Helm:
```
lvmd:
  deviceClasses:
    - name: ssd
      volume-group: myvg1
      default: true
      spare-gb: 5
node:
  kubeletWorkDirectory: ${KUBELETPATH}
controller:
  storageCapacityTracking:
    enabled: true
storageClasses:
  - name: topolvm-provisioner  # Defines name of storage class
    storageClass:
      fsType: ext4
      isDefaultClass: true
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
webhook:
  existingCertManagerIssuer:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
  podMutatingWebhook:
    enabled: false
  pvcMutatingWebhook:
    enabled: true
podSecurityPolicy:
  create: false
```
