### ISSUE TITLE
k3s and topolvm on a single node

### ISSUE THREAD

**Issue by anttilinno** [topolvm/topolvm#994]
I am at my wits end to get topolvm running on a single node. Maybe I'm missing something obvious.

```
Client Version: v1.31.2+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.2+k3s1

kubectl get node -o json | jq '.items[] | {"name": .metadata.name, "annotations": .metadata.annotations}'
{
  "name": "base",
  "annotations": {
    "alpha.kubernetes.io/provided-node-ip": "192.168.0.183",
    "capacity.topolvm.io/00default": "0",
    "capacity.topolvm.io/ssd": "0",
    "csi.volume.kubernetes.io/nodeid": "{\"topolvm.io\":\"base\"}",
    "flannel.alpha.coreos.com/backend-data": "{\"VNI\":1,\"VtepMAC\":\"6e:09:e4:2a:cd:54\"}",
    "flannel.alpha.coreos.com/backend-type": "vxlan",
    "flannel.alpha.coreos.com/kube-subnet-manager": "true",
    "flannel.alpha.coreos.com/public-ip": "192.168.0.183",
    "k3s.io/hostname": "base",
    "k3s.io/internal-ip": "192.168.0.183",
    "k3s.io/node-args": "[\"server\"]",
    "k3s.io/node-config-hash": "====",
    "k3s.io/node-env": "{\"K3S_KUBECONFIG_MODE\":\"644\"}",
    "node.alpha.kubernetes.io/ttl": "0",
    "volumes.kubernetes.io/controller-managed-attach-detach": "true"
  }
}

[root@base ~]# pvs
  PV         VG         Fmt  Attr PSize  PFree
  /dev/sdb   VG-topolvm lvm2 a--  <8.00g <8.00g

[root@base ~]# vgs
  VG         #PV #LV #SN Attr   VSize  VFree
  VG-topolvm   1   0   0 wz--n- <8.00g <8.00g

kubectl create ns topolvm-system
kubectl label namespace topolvm-system topolvm.io/webhook=ignore
kubectl label namespace kube-system topolvm.io/webhook=ignore
helm install --namespace=topolvm-system topolvm topolvm/topolvm -f values.yaml
```
**values.yaml**
```
scheduler:
  enabled: false

controller:
  replicaCount: 1
  storageCapacityTracking:
    enabled: true

lvmd:
  managed: true
  socketName: /run/topolvm/lvmd.sock
  deviceClasses:
    - name: ssd
      volume-group: VG-topolvm
      default: true
      spare-gb: 8

storageClasses:
  - name: ssd-local
    storageClass:
      fsType: btrfs
      reclaimPolicy: Delete
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
```

**Environments**
- Version:
- OS: `Linux base 6.12.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000 x86_64 GNU/Linux` in VirtualBox

```
NAME                                  READY   STATUS    RESTARTS   AGE
topolvm-controller-6975886bd5-67nlh   5/5     Running   0          20m
topolvm-lvmd-0-cqdtz                  1/1     Running   0          20m
topolvm-node-b9jfs                    3/3     Running   0          20m

# k get storageclass
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  9d
ssd-local              topolvm.io              Delete          WaitForFirstConsumer   true                   29m
```

**my-pvc.yaml**
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd-local
```
**my-pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

```
k describe pod task-pv-pod
Name:             task-pv-pod
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Containers:
  task-pv-container:
    Image:        nginx
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /usr/share/nginx/html from task-pv-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-l7jzp (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  task-pv-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-pvc
    ReadOnly:   false
  kube-api-access-l7jzp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m20s  default-scheduler  0/1 nodes are available: 1 node(s) did not have enough free storage. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

**Expected behavior**
It should work :)
